# Generated by Django 6.1.1 on 2026-09-03 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_cuti', models.CharField(choices=[('tahunan', 'Cuti Tahunan'), ('sakit', 'Cuti Sakit'), ('khusus', 'Cuti Khusus')], max_length=20)),
                ('keterangan_cuti_khusus', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_cuti', models.CharField(max_length=255)),
                ('jumlah_hari', models.PositiveIntegerField()),
                ('pengalihan_status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('pengalihan_catatan', models.TextField(blank=True, null=True)),
                ('pengalihan_tanggal_respon', models.DateTimeField(blank=True, null=True)),
                ('masuk_kerja_pada_tanggal', models.DateField()),
                ('kontak_selama_cuti', models.CharField(max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('menunggu_konfirmasi_pengalihan', 'Menunggu Konfirmasi Pengalihan'), ('ditolak_pengalihan', 'Ditolak Pengalihan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('selesai', 'Selesai')], default='menunggu_konfirmasi_pengalihan', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('pengalihan_kepada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pekerjaan_dialihkan', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_role', models.CharField(blank=True, choices=[('bod', 'BOD')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tanggal_approval', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_dilakukan', to='employees.employee')),
                ('required_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_tugas', to='employees.employee')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leaves.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='HRReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hak_saldo_cuti', models.PositiveIntegerField()),
                ('pengajuan_total_cuti', models.PositiveIntegerField()),
                ('sisa_saldo_cuti', models.PositiveIntegerField()),
                ('hr_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviews_dibuat', to='employees.employee')),
                ('leave_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_review', to='leaves.leaverequest')),
            ],
        ),
    ]
