# Generated by Django 6.1.1 on 2026-09-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField()),
                ('jenis_cuti', models.CharField(choices=[('tahunan', 'Cuti Tahunan'), ('sakit', 'Cuti Sakit'), ('khusus', 'Cuti Khusus')], max_length=20)),
                ('terpakai', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'tahun', 'jenis_cuti'), name='unique_saldo_per_tahun_jenis')],
            },
        ),
    ]
