# Generated by Django 6.1.1 on 2026-09-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (revisi pengalihan)'), ('menunggu_konfirmasi_pengalihan', 'Menunggu Konfirmasi Pengalihan'), ('ditolak_pengalihan', 'Ditolak Pengalihan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('selesai', 'Selesai')], default='menunggu_konfirmasi_pengalihan', max_length=30),
        ),
    ]
