# Generated by Django 6.1.1 on 2026-09-03 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=10, unique=True, verbose_name='NIP')),
                ('nama', models.CharField(max_length=255)),
                ('tanggal_masuk', models.DateField()),
                ('jabatan', models.CharField(max_length=100)),
                ('departemen_divisi', models.CharField(max_length=100, verbose_name='Departemen/Divisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_atasan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bawahan', to='employees.employee')),
            ],
        ),
    ]
